Chapter6
DerekAmuna/mlops-zoomcamp pull request #14
Opened 2024-11-22 15:50 UTC by DerekAmuna

Chapter on ci/cd with github actions, infrastructure as code with terraform on aws/localstack, unit and integration tests with pytest, linting and formatting with black, isort and pylint.

2024-11-28 21:45 UTC, Silas-Asamoah requested changes
Kindly include a Loom video of you having this working

2024-11-29 17:06 UTC, DerekAmuna commented
# loom video:
https://www.loom.com/share/07a5a431b894481d9d86e049aaee78be?sid=f28eee47-9be1-4dc3-9bbf-ae46288c56c3

2024-12-04 08:30 UTC, emmanuelkyeremeh approved these changes

2025-01-14 10:38 UTC, Silas-Asamoah approved these changes

2025-01-14 10:38 UTC, merged