Chapter3
DerekAmuna/mlops-zoomcamp pull request #2
Opened 2024-10-31 23:16 UTC by DerekAmuna

# chapter 3 Mage_ai pipelines

mage_ai pipelines with mlflow experiment tracking

completed homework3

2024-11-01 08:46 UTC, Silas-Asamoah requested changes
There are merge conflicts in this PR, kindly resolve them

2024-11-01 10:02 UTC, DerekAmuna commented
rebased the branch. should be no more conflicts

2024-11-06 09:25 UTC, emmanuelkyeremeh approved these changes

2024-11-07 14:45 UTC, Silas-Asamoah approved these changes
Looks good, .DS store should be deleted and gitignored

2024-11-07 14:45 UTC, merged