Chapter4
DerekAmuna/mlops-zoomcamp pull request #3
Opened 2024-11-07 13:17 UTC by DerekAmuna

# Chapter 4 deployment methods
Please do let me know when chapter 3 pr and this pr are approved so i can rebase before merging to avoid conflicts again

2024-11-07 17:57 UTC, emmanuelkyeremeh approved these changes

2024-11-12 08:23 UTC, emmanuelkyeremeh approved these changes

2024-11-14 09:43 UTC, Silas-Asamoah requested changes
Left some inline comments , kindly check it out

2024-11-14 09:43 UTC, Silas-Asamoah commented on chapter4/webservice/intro_lm.bin
This file should be gitignored

2024-11-14 09:43 UTC, Silas-Asamoah commented on chapter4/webservice/dv.bin
This file should be gitignored

2024-11-14 09:43 UTC, Silas-Asamoah commented on chapter4/webservice/mlflow_artifacts/1/64b1755f573c4439974d9f5ab58a9a06/artifacts/dv.bin
This file should be gitignored

2024-11-14 09:43 UTC, Silas-Asamoah commented on chapter4/webservice/mlflow_artifacts/dv.bin
This file should be gitignored

2024-11-14 09:43 UTC, Silas-Asamoah commented on chapter4/webservice/predict.py
> +MLFLOW_TRACKING_URI = "http://127.0.0.1:5000"
This should be read from an environment variable and not hard coded

2024-11-14 09:43 UTC, Silas-Asamoah commented on chapter4/webservice/predict2.py
> +MLFLOW_TRACKING_URI = "http://127.0.0.1:5000"
Likewise here

2024-11-14 09:43 UTC, Silas-Asamoah commented on chapter4/webservice/predict3.py
> +MLFLOW_TRACKING_URI = "http://127.0.0.1:5000"
Here as well

2024-11-14 09:43 UTC, Silas-Asamoah commented on homework/chapter4/intro_lm.bin
This file should be gitignored

2024-11-14 11:14 UTC, Silas-Asamoah requested changes
Great job on the comments, just one last thing on the environment variables with Docker and this PR should be good to go

2024-11-14 11:14 UTC, Silas-Asamoah commented on homework/chapter4/dockerfile
> +ENV MLFLOW_TRACKING_URI=http://127.0.0.1:5000
This is still hardcoded and shouldn't be in your Dockerfile. Create a `.env`(this should be gitignored) and read the tracking URI from there. Here's a StackOverflow link on this 
https://stackoverflow.com/questions/46917831/how-to-load-several-environment-variables-without-cluttering-the-dockerfile/46925953

2024-11-15 10:14 UTC, Silas-Asamoah approved these changes

2024-11-15 10:14 UTC, merged